
def buildPK_1 (L):
    out = open("pk1.vtk","w+")
    out.write("# vtk DataFile Version 3.0\n")
    out.write("Purkinje\nASCII\nDATASET POLYDATA\n")
    out.write("POINTS 9 float\n")
    out.write("%.6f %.6f %.6f\n" % (0,0,0))
    out.write("%.6f %.6f %.6f\n" % (L,0,0))
    out.write("%.6f %.6f %.6f\n" % (2*L,-L,0))
    out.write("%.6f %.6f %.6f\n" % (3*L,0,0))
    out.write("%.6f %.6f %.6f\n" % (4*L,0,0))
    out.write("%.6f %.6f %.6f\n" % (5*L,L,0))
    out.write("%.6f %.6f %.6f\n" % (5*L,2*L,0))
    out.write("%.6f %.6f %.6f\n" % (6*L,L,0))
    out.write("%.6f %.6f %.6f\n" % (5*L,-L,0))
    out.write("LINES 8 24\n")
    out.write("2 %d %d\n" % (0,1))
    out.write("2 %d %d\n" % (1,2))
    out.write("2 %d %d\n" % (1,3))
    out.write("2 %d %d\n" % (3,4))
    out.write("2 %d %d\n" % (4,5))
    out.write("2 %d %d\n" % (4,8))
    out.write("2 %d %d\n" % (5,6))
    out.write("2 %d %d\n" % (5,7))
    out.close()

def buildPK_2 (L):
    out = open("pk2.vtk","w+")
    out.write("# vtk DataFile Version 3.0\n")
    out.write("Purkinje\nASCII\nDATASET POLYDATA\n")
    out.write("POINTS 17 float\n")
    out.write("%.6f %.6f %.6f\n" % (0,0,0))
    out.write("%.6f %.6f %.6f\n" % (L,0,0))
    out.write("%.6f %.6f %.6f\n" % (2*L,-L,0))
    out.write("%.6f %.6f %.6f\n" % (2*L,0,0))
    out.write("%.6f %.6f %.6f\n" % (3*L,0,0))
    out.write("%.6f %.6f %.6f\n" % (4*L,L,0))
    out.write("%.6f %.6f %.6f\n" %(4*L,2*L,0))
    out.write("%.6f %.6f %.6f\n" %(4*L,3*L,0))
    out.write("%.6f %.6f %.6f\n" %(5*L,2*L,0))
    out.write("%.6f %.6f %.6f\n" %(6*L,3*L,0))
    out.write("%.6f %.6f %.6f\n" %(4*L,0,0))
    out.write("%.6f %.6f %.6f\n" %(5*L,0,0))
    out.write("%.6f %.6f %.6f\n" %(6*L,L,0))
    out.write("%.6f %.6f %.6f\n" %(6*L,-L,0))
    out.write("%.6f %.6f %.6f\n" %(6*L,-2*L,0))
    out.write("%.6f %.6f %.6f\n" %(7*L,-2*L,0))
    out.write("%.6f %.6f %.6f\n" %(7*L,-3*L,0))
    out.write("LINES 16 48\n")
    out.write("2 %d %d\n" %(0,1))
    out.write("2 %d %d\n" %(1,2))
    out.write("2 %d %d\n" %(1,3))
    out.write("2 %d %d\n" %(3,4))
    out.write("2 %d %d\n" %(4,5))
    out.write("2 %d %d\n" %(5,6))
    out.write("2 %d %d\n" %(6,7))
    out.write("2 %d %d\n" %(5,8))
    out.write("2 %d %d\n" %(8,9))
    out.write("2 %d %d\n" %(4,10))
    out.write("2 %d %d\n" %(10,11))
    out.write("2 %d %d\n" %(11,12))
    out.write("2 %d %d\n" %(11,13))
    out.write("2 %d %d\n" %(10,14))
    out.write("2 %d %d\n" %(14,15))
    out.write("2 %d %d\n" %(14,16))
    out.close()

def main ():
    buildPK_1(0.5)
    buildPK_2(0.5)

if __name__ == "__main__":
    main()